platform :ios, '8.0'

target 'MeppSDK-Demo-Objc' do
  use_frameworks!

  pod 'MeppSDK', :git => 'https://github.com/mopius/mepp-ios-sdk.git'
end

post_install do |installer_representation|
  # Specify Swift 2.3 Setting!
  installer_representation.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '2.3'
    end 
  end 
end
